services:
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - back-end
    restart: unless-stopped

  backend:
    build: ./backend
    command: sh -c "python manage.py migrate --no-input && python manage.py collectstatic --no-input && gunicorn --bind 0.0.0.0:8000 core.wsgi:application"
    volumes:
      - ./backend:/app
      - media:/backend/media
      - staticfiles:/backend/staticfiles
    #    ports:
    #      - "8000:8000"
    env_file:
      - .env
    environment:
      - POSTGRES_NAME=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - STORE_WHATSAPP_NUMBER=${STORE_WHATSAPP_NUMBER}
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/admin/login/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - front-end
      - back-end
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_USE_MERCADOPAGO: ${VITE_USE_MERCADOPAGO}
        VITE_MERCADOPAGO_PUBLIC_KEY: ${VITE_MERCADOPAGO_PUBLIC_KEY}
    # ports:
    #  - "8088:80"
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - media:/app/media
      - staticfiles:/app/staticfiles
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - front-end
      - back-end
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=front-end"
      # HTTPS router for frontend
      - "traefik.http.routers.triplice-frontend.rule=Host(`triplice3d.com.br`)"
      - "traefik.http.routers.triplice-frontend.entrypoints=websecure"
      - "traefik.http.routers.triplice-frontend.tls.certresolver=myresolver"
      - "traefik.http.services.triplice-frontend.loadbalancer.server.port=80"
      # HTTP -> HTTPS redirect for frontend
      - "traefik.http.routers.triplice-frontend-http.rule=Host(`triplice3d.com.br`)"
      - "traefik.http.routers.triplice-frontend-http.entrypoints=web"
      - "traefik.http.routers.triplice-frontend-http.middlewares=redirect-to-https"

networks:
  front-end:
    external: true
  back-end:
    external: true

volumes:
  postgres_data:
  media:
  staticfiles:
