# Generated by Django 6.0.1 on 2026-02-02 06:58

import apps.store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=apps.store.models.generate_order_number, editable=False, max_length=8, unique=True),
        ),
    ]
