# Generated by Django 6.0.1 on 2026-02-06 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_product_category_product_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionalPopup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='popups/')),
                ('link_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('frequency', models.CharField(choices=[('SESSION', 'Every Session'), ('ONCE', 'Once per User'), ('PERIOD', 'Periodically (every X days)')], default='ONCE', max_length=20)),
                ('period_days', models.PositiveIntegerField(blank=True, help_text='Used if frequency is Periodically', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
