# Generated by Django 6.0.1 on 2026-02-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_default',
            field=models.BooleanField(default=False, help_text='If checked, this category will be pre-selected on the storefront'),
        ),
    ]
