# Generated by Django 6.0.1 on 2026-03-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_options_remove_color_hex_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, help_text='Ex: 10x15x20cm', max_length=100, verbose_name='Tamanho'),
        ),
    ]
